ui: mocha-bdd
browsers:
  - name: chrome
    version: 55..latest
  - name: firefox
    version: 50..latest
  - name: opera
    version: 11..latest
  - name: safari
    version: 6..latest
  - name: ipad
    version: 6.1
  - name: iphone
    version: 6.1